### PR TITLE
new version: upgrade to v9.3.0

### PR DESCRIPTION
**Pull request by GregoryEssertel**
Summary:
Added
- A new `-tc-suggestion/--time-constraints-are-suggestion` flag to `exec`.
- A new `--no-redirect` flag to `exec`. It allows the endpoint of the scle test
  workcell instance to be used, instead of the client dashboard.

Fixed
- The workcell id in `exec` was forced to be `wcN`. There is now no restrictions.

Updated
- Added support for sessions and absolute time constraint in `exec` CLI command.
  Added "--sessionId", "--schedule-at", and "--schedule-delay" flags.
- The api url expected by the `exec` method has been changed to be the url of
  the new dashboard (unless `--no-redirect` is used). It has the shape:
  `base_url/facility/workcell`. It does not require `http` to be added anymore.

### CODE REVIEW

**Review by yangchoo — COMMENTED** [review]
Technically this should be 9.3.0 since there are features in this release

**Review by yangchoo — APPROVED** [review]
Approved if updated to 9.3.0.
Remember to push the tag once merged

**Comment by GregoryEssertel** [comment]
updated to 0.9.3 and I also added some changes I just merged.

**Review by yangchoo — APPROVED** [review]
thanks!

**Pull request merged**
