### PR TITLE
new version: upgrade to v9.3.1

### PR DESCRIPTION
**Pull request by GregoryEssertel**
Summary:

Fixed
- Adapt the backend url resolution with the new configuration of the frontend client.

----------

Need that for compatibility with Monday's deployment

### CODE REVIEW

**Review by aaronstrateos — COMMENTED** [review]
I only see changelog and version update. Just want to make sure you didn't leave out the actual changes specified in the changelog.

**Comment by GregoryEssertel** [comment]
> I only see changelog and version update. Just want to make sure you didn't leave out the actual changes specified in the changelog.

The changes are the previous commit.

**Review by aaronstrateos — APPROVED** [review]

**Comment by GregoryEssertel** [comment]
I will merge on Monday after deployment!

**Review by yangchoo — APPROVED** [review]
thanks!

**Pull request merged**
