### PR TITLE
build: Cache Binder Build Step

### PR DESCRIPTION
**Pull request by yangchoo**
Utilize GitHub action to cache the Binder build step. Only enable this
step on master so that we'll only build upon merge to master.

### CODE REVIEW

**Comment by yangchoo** [comment]
See https://github.com/strateos/transcriptic/actions/runs/460714691 for an example triggered build. That was done by relaxing the push restriction from master to `*`

**Comment by dzleidig** [comment]
After reading up in the repo2docker-action repo, I think I get the gist of this, but there I still have some disconnects -  let's discuss.

https://github.com/jupyterhub/repo2docker-action#what-can-i-do-with-this-action
> You can use this Action to pre-cache Docker images to a Docker registry that you can reference in your repo. For example if you have the file Dockerfile in the binder/ directory relative to the root of your repository with the following contents, this will allow Binder to start quickly by pulling an image you have already built:

> ### This is the image that is built and pushed by this Action (replace this with your image name)
> ``` 
> FROM myorg/myimage:latest
>...
> ```

Don't we have to reference the image that is being cached in order for us to leverage the fact that it's being cached?

**Comment by dzleidig** [comment]
They also give multiple examples of caching it on branches/PRs. Is our intention to only speed up the binder on master?

**Review by dzleidig — APPROVED** [review]
Approving for now, but let's discuss those talking points prior to merging,

**Pull request merged**
