### PR TITLE
build: Migrate notebooks directory

### PR DESCRIPTION
**Pull request by yangchoo**
Part of a process to breakout the notebooks directory into a
separate branch for easier maintainence.
All subsequent notebook PRs should be made against the notebooks branch.

This PR removes notebooks, updates the binderhub link to reference
the new layout and updates the documentation.

### CODE REVIEW

**Comment by yangchoo** [comment]
To preview the change, change the link to reference this branch instead of master (this will work once merged on master):
https://mybinder.org/v2/gh/strateos/transcriptic/nbgitpuller?urlpath=git-pull%3Frepo%3Dhttps%253A%252F%252Fgithub.com%252Fstrateos%252Ftranscriptic%26urlpath%3Dtree%252Ftranscriptic%252F%26branch%3Dnotebooks

The notebooks will live separately on https://github.com/strateos/transcriptic/tree/notebooks
That way, we can update and organize both separately (no need to run CI on notebooks changes for example), and its easier to separate function from demo. 
Keeping them to the same repo for now so that its easier to cross-reference, i.e. its obvious that the notebooks are for this particular library. This pattern seems to be used in other OSS repos as well.

**Comment by dzleidig** [comment]
Is our intention to move them to a separate repo eventually? Using a branch for this purpose seems unconventional to me, but I suppose you it's common in other OSS as you say. What is our strategy for updating the notebooks branch and keeping it in line w/ master? (or with the latest release?)

**Comment by yangchoo** [comment]
@dzleidig 

>  What is our strategy for updating the notebooks branch and keeping it in line w/ master? (or with the latest release?)

If you're referring to ensuring that the notebooks cells can always execute on the master branch, that's a good point. Yea, I'll look into it and see if there's a CI step we can add to execute all cells of the notebooks and ensure that they can execute fine.

Seems like this may work: https://pytest-notebook.readthedocs.io/en/latest

**Comment by ramu-phanimukla** [comment]
> Is our intention to move them to a separate repo eventually? Using a branch for this purpose seems unconventional to me, but I suppose you it's common in other OSS as you say. What is our strategy for updating the notebooks branch and keeping it in line w/ master? (or with the latest release?)

I agree with Dylan on using branch is not conventional. Branches are meant to eventually merged to master. I am in favor of maintaining notebooks in separate repo and let it point to this repo, wherever it is needed.

**Comment by yangchoo** [comment]
I'm open to shifting it to a separate repository.

It'll require slightly more work to run CI, but its all in all not too bad.

**Comment by yangchoo** [comment]
Shifted notebooks to a separate repo: https://github.com/open-strateos/txpy_jupyter_notebooks

Try it with this link: (point `.../transcriptic/master?` to this branch, i.e. `..,/transcriptic/nbgitpuller?`)
https://mybinder.org/v2/gh/strateos/transcriptic/nbgitpuller?urlpath=git-pull%3Frepo%3Dhttps%253A%252F%252Fgithub.com%252Fopen-strateos%252Ftxpy_jupyter_notebooks%26urlpath%3Dtree%252Ftxpy_jupyter_notebooks%252Findex.ipynb%26branch%3Dmain

**Comment by dzleidig** [comment]
Ok, I think this makes sense....and I suppose after merging this, the binder link in the https://github.com/open-strateos/txpy_jupyter_notebooks will start to work.

**Review by dzleidig — APPROVED** [review]
Ok, I think this makes sense....and I suppose after merging this, the binder link in the https://github.com/open-strateos/txpy_jupyter_notebooks readme will start to work.

**Pull request merged**
